stages:
  - build
  - test
  - deploy

build:
  script:
    - go build
    
test:
  script:
    - go test -v -cover
    
deploy:
  only:
    - refs:
      - master
    - tags
  script:
    - curl -sL https://git.io/goreleaser | bash