default:
  image: golang

stages:
  - build
  - test
  - deploy

build:
  script:
    - go build
    
test:
  script:
    - go test -race -v ./... -cover
    
deploy:
  only:
    - master
    - tags
  script:
    - curl -sL https://git.io/goreleaser | bash